name: pr_to_main

on:
  pull_request:

env:
  DBT_PROFILES_DIR: ./
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  NESTUITE_SOURCE_SCHEMA: ${{ secrets.NESTUITE_SOURCE_SCHEMA }}

jobs:
  pr_to_main:
    name: pr_to_main
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x" # not specifying the patch version allows for faster setup
          cache: 'pip'

      - name: Install python & dbt dependencies
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Run all models
        id: run_all_models
        run: dbt run

      - name: Test all models
        id: test_all_models
        run: dbt test
          
      - name: Lint dbt models
        id: sqlfluff_json
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
          git diff ${{ github.event.pull_request.base.ref }} --name-only --diff-filter=d | egrep '^models/.*sql$$' | xargs -r sqlfluff lint --format github-annotation --annotation-level failure --nofail --write-output annotations.json     

      - name: Annotate the Changes Files in PR
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          input: './annotations.json'          
